"""empty message

Revision ID: 621cfda3d7bc
Revises: ca7dec5a67b9
Create Date: 2024-11-30 23:10:31.841051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621cfda3d7bc'
down_revision = 'ca7dec5a67b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'professional', ['professional_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'professional', ['professional_id'], ['id'])
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'])

    # ### end Alembic commands ###
