"""empty message

Revision ID: 98981b878270
Revises: 8726ed42f4cb
Create Date: 2024-11-30 23:53:49.378908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98981b878270'
down_revision = '8726ed42f4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.alter_column('flag',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.alter_column('flag',
               existing_type=sa.String(length=30),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
